version: '3'

services:
    app:
        image: reassembleudp
        build: .
        ports:
            - 27017:27017
        volumes:
            - .:/app
            - nix:/nix
        environment:
            - MONGO_URI=mongodb://0.0.0.0:27017
            - PROTO=udp
            - IP=0.0.0.0
            - PORT=6789
            - NIXPKGS_ALLOW_UNFREE=1
        restart: no
        stdin_open: true
        tty: true
        working_dir: /app
        command: bash -c ./scripts/run.sh
volumes:
    nix:
