version: '3'

services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
    app:
        image: reassembleudp
        build: .
        volumes:
            - .:/app
            - nix:/nix
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://mongodb:27017
            - PROTO=udp
            - IP=0.0.0.0
            - PORT=6789
        restart: no
        stdin_open: true
        tty: true
        working_dir: /app
        command: bash -c ./scripts/run.sh
volumes:
    nix:
